name: coughingcatcoin-core # you probably want to 'snapcraft register <name>'
version: '1.14.4'
summary: Reference client of Coughingcatcoin, a peer-to-peer digital currency like Bitcoin.
description: |
  Coughingcatcoin is a cryptocurrency like Bitcoin, although it does not use SHA256 as its proof of work (POW). Taking development cues from Tenebrix and Litecoin, Coughingcatcoin currently employs a simplified variant of scrypt. MIT licenced.

base: core18
grade: stable
confinement: strict
architectures:
  - build-on: [amd64, i386, arm64]

apps:
  d:
    command: coughingcatcoind
    plugs: [home, removable-media, network, network-bind]
    environment:
    # Override HOME so the datadir is located at ~/snap/coughingcatcoin-core/common/.coughingcatcoin/ instead of ~/snap/coughingcatcoin-core/current/.coughingcatcoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: qt4-launch coughingcatcoin-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: coughingcatcoin-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  coughingcatcoin-core:
    plugin: nil
    override-build: |
      echo "Downloading files..."
      wget https://github.com/coughingcatcoin/coughingcatcoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/coughingcatcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      wget https://github.com/coughingcatcoin/gitian.sigs/archive/refs/heads/master.zip
      unzip master.zip
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum coughingcatcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz)
      if ! grep -r $checksum *; then
        echo "Secure hash not verified."
        return
      fi
      tar -xvf coughingcatcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      coughingcatcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_coughingcatcoin
      echo "Installing Coughingcatcoin..."
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin coughingcatcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/coughingcatcoind
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin coughingcatcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/coughingcatcoin-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin coughingcatcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/coughingcatcoin-cli
      wget https://raw.githubusercontent.com/coughingcatcoin/coughingcatcoin/v${SNAPCRAFT_PROJECT_VERSION}/share/pixmaps/bitcoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps bitcoin128.png
    build-packages:
      - unzip
      - wget
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libx11-xcb1
      - libx11-6
      - libfontconfig
  qt4conf:
    build-packages:
      - dpkg-dev
    plugin: make
    source: https://github.com/kyrofa/qt4conf.git
